### ISSUE TITLE
data and label format description 

### ISSUE THREAD

**Issue by ysm022** [VIS-VAR/LGSC-for-FAS#14]
The ff++ dataset is too big to download. Can you provide the train_add_train.txt? or provide the data and label format description in train_add_train.txt？Thanks

**Comment by ZGSLZL** [comment]
Hi, @ysm022 , thanks for you question, here is the sample of train label file
[train_label_format.txt](https://github.com/VIS-VAR/LGSC-for-FAS/files/4762345/train_label_format.txt)，Note that label 1 is fake and 0 is real.

**Comment by ysm022** [comment]
Hello, I use 6 pics as train input, including 3 real and 3 fake. 2 pics as val. 
then I run train.py. get error as follow

Traceback (most recent call last):
  File "train.py", line 101, in <module>
    runner.train(max_epochs=15)
  File "/data/ysm/liveDetection/LGSC-for-FAS-master/utils/runner.py", line 208, in train
    score = self.val()
  File "/data/ysm/liveDetection/LGSC-for-FAS-master/utils/runner.py", line 171, in val
    cue = self.model(imgs, label, return_loss=False)
  File "/data/ysm/pyvenv/test/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/ysm/liveDetection/LGSC-for-FAS-master/models/scan.py", line 127, in forward
    outs = self.neck(outs)
  File "/data/ysm/pyvenv/test/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/ysm/liveDetection/LGSC-for-FAS-master/models/scan.py", line 75, in forward
    out = self.conv2x2[i](out)
  File "/data/ysm/pyvenv/test/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/ysm/liveDetection/LGSC-for-FAS-master/utils/conv_module.py", line 117, in forward
    x = self.norm(x)
  File "/data/ysm/pyvenv/test/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/ysm/liveDetection/LGSC-for-FAS-master/utils/norm_module.py", line 106, in forward
    outs = core.ops.instance_norm(inputs, attrs, outputs)
TypeError: instance_norm(): incompatible function arguments. The following argument types are supported:
    1. (arg0: paddle::imperative::VarBase, arg1: paddle::imperative::VarBase, arg2: paddle::imperative::VarBase, *args) -> Tuple[paddle::imperative::VarBase, paddle::imperative::VarBase, paddle::imperative::VarBase]

Invoked with: {'X': [<paddle.fluid.core_avx.VarBase object at 0x7fb02c429b58>], 'Scale': [name instance_norm_5.w_0, dtype: VarType.FP32 shape: [256] 	lod: {}
	dim: 256
	layout: NCHW
	dtype: float
	data: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
], 'Bias': [name instance_norm_5.b_0, dtype: VarType.FP32 shape: [256] 	lod: {}
	dim: 256
	layout: NCHW
	dtype: float
	data: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
]}, {'momentum': 0.9, 'epsilon': 1e-05, 'is_test': True, 'data_layout': 'NCHW', 'use_mkldnn': False, 'fuse_with_relu': False, 'use_global_stats': False, 'trainable_statistics': False}, {'Y': [<paddle.fluid.core_avx.VarBase object at 0x7fb02c429ae8>], 'SavedMean': [<paddle.fluid.core_avx.VarBase object at 0x7fb02c429570>], 'SavedVariance': [<paddle.fluid.core_avx.VarBase object at 0x7fb02c429c70>]}

Can you tell me why, Thank you very much

**Comment by MagicXiaoJing** [comment]
> Hi, @ysm022 , thanks for you question, here is the sample of train label file
> [train_label_format.txt](https://github.com/VIS-VAR/LGSC-for-FAS/files/4762345/train_label_format.txt)，Note that label 1 is fake and 0 is real.

    def get_losses(self, out, cls_out, mask, gt_labels):
        loss_cls = L.mean(L.cross_entropy(cls_out, gt_labels)) * self.train_cfg['w_cls']
        # 1 real 0 fake
        cue = out[-1] if self.train_cfg['with_mask'] else L.elementwise_mul(
            out[-1], L.cast(gt_labels, 'float32'), axis=0)
        num_reg = L.cast(L.reduce_sum(gt_labels) * cue.shape[1] * cue.shape[2] * cue.shape[3], 'float32')
        loss_reg = L.reduce_sum(L.abs(mask - cue)) / (num_reg + 1e-8) * self.train_cfg['w_reg']
        loss_tir = 0
        for feat in out[:-1]:
            feat = L.squeeze(self.avgpool(feat), axes=[2, 3])
            loss_tir += self.triple_loss(feat, gt_labels) * self.train_cfg['w_tri']
        loss = loss_cls + loss_reg + loss_tir
        return dict(loss_cls=loss_cls, loss_reg=loss_reg, loss_tir=loss_tir, loss=loss)

in this coding: 0 is fake , 1 is real。  ？？！！

**Comment by ysm022** [comment]
Now I update train_add_train.txt and train_val_train.txt, I sure label 1 is fake and 0 is real. But run train.py.  
Get error as same. 

--------------------------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    runner.train(max_epochs=15)
  File "/data/ysm/liveDetection/LGSC-for-FAS-master/utils/runner.py", line 208, in train
    score = self.val()
  File "/data/ysm/liveDetection/LGSC-for-FAS-master/utils/runner.py", line 171, in val
    cue = self.model(imgs, label, return_loss=False)
  File "/data/ysm/pyvenv/test/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/ysm/liveDetection/LGSC-for-FAS-master/models/scan.py", line 127, in forward
    outs = self.neck(outs)
  File "/data/ysm/pyvenv/test/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/ysm/liveDetection/LGSC-for-FAS-master/models/scan.py", line 75, in forward
    out = self.conv2x2[i](out)
  File "/data/ysm/pyvenv/test/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/ysm/liveDetection/LGSC-for-FAS-master/utils/conv_module.py", line 117, in forward
    x = self.norm(x)
  File "/data/ysm/pyvenv/test/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/ysm/liveDetection/LGSC-for-FAS-master/utils/norm_module.py", line 106, in forward
    outs = core.ops.instance_norm(inputs, attrs, outputs)
TypeError: instance_norm(): incompatible function arguments. The following argument types are supported:
    1. (arg0: paddle::imperative::VarBase, arg1: paddle::imperative::VarBase, arg2: paddle::imperative::VarBase, *args) -> Tuple[paddle::imperative::VarBase, paddle::imperative::VarBase, paddle::imperative::VarBase]

Invoked with: {'X': [<paddle.fluid.core_avx.VarBase object at 0x7f6a328c0ae8>], 'Scale': [name instance_norm_5.w_0, dtype: VarType.FP32 shape: [256] 	lod: {}
	dim: 256
	layout: NCHW
	dtype: float
	data: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
], 'Bias': [name instance_norm_5.b_0, dtype: VarType.FP32 shape: [256] 	lod: {}
	dim: 256
	layout: NCHW
	dtype: float
	data: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
]}, {'momentum': 0.9, 'epsilon': 1e-05, 'is_test': True, 'data_layout': 'NCHW', 'use_mkldnn': False, 'fuse_with_relu': False, 'use_global_stats': False, 'trainable_statistics': False}, {'Y': [<paddle.fluid.core_avx.VarBase object at 0x7f6a328c0a78>], 'SavedMean': [<paddle.fluid.core_avx.VarBase object at 0x7f6a328c0500>], 'SavedVariance': [<paddle.fluid.core_avx.VarBase object at 0x7f6a328c0c00>]}
--------------------------------------------------------------------

So what can I do?

**Comment by ZGSLZL** [comment]
Hi, @ysm022 , You can refer to [issuse](https://github.com/VIS-VAR/LGSC-for-FAS/issues/15)

**Comment by ysm022** [comment]
The error in utils/norm_module.py 106 row: outs = core.ops.instance_norm(inputs, attrs, outputs)

**Comment by ZGSLZL** [comment]
Hi, @MagicXiaoJing , we changed the label after loading the label file.
`                if int(item[1]) == 0:
                    pos_infos.append(dict(
                        img_path=item[0],
                        label=1 - int(item[1])))
                else:
                    neg_infos.append(dict(
                        img_path=item[0],
                        label=1 - int(item[1])))`

**Comment by ZGSLZL** [comment]
@ysm022 , you can try paddle version 1.7.1.

**Comment by MagicXiaoJing** [comment]
Thxs！

**Comment by MagicXiaoJing** [comment]
Hi, I rewrite this in pytorch, and training.
a. the things i change is replace conv2x2 with conv3x3 and remove the pad
b. replace the instance norm with batch norm
but i cannot get the mask like yours in paper.
 
![image](https://user-images.githubusercontent.com/5450325/84372097-357a9600-ac0d-11ea-88f4-f765aa206758.png)

is there any other trick ??

**Comment by ZGSLZL** [comment]
Hi, @MagicXiaoJing , thanks for you questions, it is not recommended to change these first, and then it must be emphasized that the instance norm must be used in the decoder.

**Comment by lz28lz28** [comment]
> Hi, I rewrite this in pytorch, and training.
> a. the things i change is replace conv2x2 with conv3x3 and remove the pad
> b. replace the instance norm with batch norm
> but i cannot get the mask like yours in paper.
> 
> ![image](https://user-images.githubusercontent.com/5450325/84372097-357a9600-ac0d-11ea-88f4-f765aa206758.png)
> 
> is there any other trick ??

Hi, i also rewrite this in pytorch, training and also make changes like u. Can u leave email or other method for contact? Mine is 1030615223@vip.jiangnan.edu.cn.

**Comment by MagicXiaoJing** [comment]
> email or other method for contact? M

wechar:18200519211

**Comment by ysm022** [comment]
@ZGSLZL thanks, update to 1.7.1, that's ok.

**Comment by yuchunwang** [comment]
> Hi, @ysm022 , thanks for you question, here is the sample of train label file
> [train_label_format.txt](https://github.com/VIS-VAR/LGSC-for-FAS/files/4762345/train_label_format.txt)，Note that label 1 is fake and 0 is real.

Could you also provide the OULU and casia dataset's data format description ? Thanks.

**Comment by CHNxindong** [comment]
@ZGSLZL hello, I am also training on oulu, can you share how to modify train.py? and do you know how to organise data format corresponding to oulu.py? thank you! thank you! thank you!!!
