### ISSUE TITLE
TypeError: instance_norm(): incompatible function arguments. 

### ISSUE THREAD

**Issue by xiao-keeplearning** [VIS-VAR/LGSC-for-FAS#15]
When I try to train OULU database, I have the following problem.
> W0611 09:39:30.550093  3574 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W0611 09:39:30.555764  3574 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2020-06-11 09:39:33,874-INFO: Loading pretrained model from ./pretrained/resnet18-torch
2020-06-11 09:39:34,297-WARNING: No pretrained model for Resnet
Total: 27.51932M  Trainable: 27.50012M
2020-06-11 09:39:34,363-INFO: Total epoch: 15, Total iter: 119655, Iter/epoch: 7977
Traceback (most recent call last):
  File "train_oulu.py", line 98, in <module>
    runner.train(max_epochs=15)
  File "/home2/xiaoyao/project/face_antispoof_rgb/LGSC-for-FAS/utils/runner.py", line 218, in train
    losses = self.model(imgs, label, mask=mask)
  File "/home2/xiaoyao/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home2/xiaoyao/project/face_antispoof_rgb/LGSC-for-FAS/models/scan.py", line 127, in forward
    outs = self.neck(outs)
  File "/home2/xiaoyao/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home2/xiaoyao/project/face_antispoof_rgb/LGSC-for-FAS/models/scan.py", line 75, in forward
    out = self.conv2x2[i](out)
  File "/home2/xiaoyao/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home2/xiaoyao/project/face_antispoof_rgb/LGSC-for-FAS/utils/conv_module.py", line 117, in forward
    x = self.norm(x)
  File "/home2/xiaoyao/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home2/xiaoyao/project/face_antispoof_rgb/LGSC-for-FAS/utils/norm_module.py", line 106, in forward
    outs = core.ops.instance_norm(inputs, attrs, outputs)
TypeError: instance_norm(): incompatible function arguments. The following argument types are supported:
    1. (arg0: paddle::imperative::VarBase, arg1: paddle::imperative::VarBase, arg2: paddle::imperative::VarBase, *args) -> Tuple[paddle::imperative::VarBase, paddle::imperative::VarBase, paddle::imperative::VarBase]
Invoked with: {'X': [<paddle.fluid.core_avx.VarBase object at 0x7fd48a1be170>], 'Scale': [name instance_norm_5.w_0, dtype: VarType.FP32 shape: [256]    lod: {}
        dim: 256
        layout: NCHW
        dtype: float
        data: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
], 'Bias': [name instance_norm_5.b_0, dtype: VarType.FP32 shape: [256]  lod: {}
        dim: 256
        layout: NCHW
        dtype: float
        data: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
]}, {'momentum': 0.9, 'epsilon': 1e-05, 'is_test': False, 'data_layout': 'NCHW', 'use_mkldnn': False, 'fuse_with_relu': False, 'use_global_stats': False, 'trainable_statistics': False}, {'Y': [<paddle.fluid.core_avx.VarBase object at 0x7fd489f3f5b0>], 'SavedMean': [<paddle.fluid.core_avx.VarBase object at 0x7fd489f3f9b0>], 'SavedVariance': [<paddle.fluid.core_avx.VarBase object at 0x7fd489f3f7f0>]}

However, when I replace Instance norm with Batch norm, code can run. Please help me, what should I do?

**Comment by ZGSLZL** [comment]
Hi， what is the version of paddle you are using？you can try paddle version 1.7.1

**Comment by xiao-keeplearning** [comment]
My version is 1.8.1. Thanks, I will try.

**Comment by xiao-keeplearning** [comment]
You're right, this problem solved.

**Comment by linnnff** [comment]
> 我的版本是1.8.1。谢谢，我会尽力的。



> 是的，这个问题解决了。

请问你是怎么解决的

**Comment by CHNxindong** [comment]
@1282522443 you can use version 1.7.1

**Comment by naserpiltan** [comment]
Hi , I checked my paddle version and it is 1.7.1.
When I run the train.py file , it gives me this error 
![Screenshot from 2021-05-02 00-13-11](https://user-images.githubusercontent.com/33447001/116793343-4685fd00-aa94-11eb-800d-3c4778ddb611.png)
could you plz give a solution?
