### ISSUE TITLE
求大佬帮助

### ISSUE THREAD

**Issue by linnnff** [VIS-VAR/LGSC-for-FAS#17]
Traceback (most recent call last):
  File "/home/gpu/user/lnn/LGSC-master/test.py", line 81, in <module>
    model = SCAN(**model_cfg)
  File "/home/gpu/user/lnn/LGSC-master/models/scan.py", line 96, in __init__
    self.backbone = ResNet(**backbone)
  File "/home/gpu/user/lnn/LGSC-master/models/resnet.py", line 258, in __init__
    self._make_stem_layer()
  File "/home/gpu/user/lnn/LGSC-master/models/resnet.py", line 296, in _make_stem_layer
    bias_attr=False)
  File "/home/gpu/user/lnn/LGSC-master/utils/conv_module.py", line 35, in build_conv_layer
    layer = conv_layer(*args, **kwargs, **cfg_)
  File "/home/gpu/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/nn.py", line 211, in __init__
    default_initializer=_get_default_param_initializer())
  File "/home/gpu/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 113, in create_parameter
    default_initializer)
  File "/home/gpu/.local/lib/python3.6/site-packages/paddle/fluid/layer_helper_base.py", line 347, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/gpu/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2476, in create_parameter
    initializer(param, self)
  File "/home/gpu/.local/lib/python3.6/site-packages/paddle/fluid/initializer.py", line 382, in __call__
    stop_gradient=True)
  File "/home/gpu/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2585, in _prepend_op
    kwargs.get("stop_gradient", False))
  File "/home/gpu/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/tracer.py", line 39, in trace_op
    not stop_gradient)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::dynload::GetCublasDsoHandle()
3   void std::__once_call_impl<std::_Bind_simple<cublasStatus_t paddle::platform::dynload::DynLoad__cublasCreate_v2::operator()<cublasContext**>(cublasContext**)::{lambda()#1} ()> >()
4   paddle::platform::CublasHandleHolder::CublasHandleHolder(CUstream_st*, cublasMath_t)
5   paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace)
6   std::_Function_handler<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > (), std::reference_wrapper<std::_Bind_simple<void paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()> > >::_M_invoke(std::_Any_data const&)
7   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
8   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
9   std::__future_base::_Deferred_state<std::_Bind_simple<void paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_run_deferred()
10  paddle::platform::DeviceContextPool::Get(paddle::platform::Place const&)
11  paddle::imperative::PreparedOp::Prepare(std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, paddle::framework::OperatorWithKernel const&, paddle::platform::Place, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > > const*)
12  paddle::imperative::OpBase::Run(std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&)
13  paddle::imperative::Tracer::TraceOp(std::string const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >, paddle::platform::Place const&, bool)

----------------------
Error Message Summary:
----------------------
Error: Failed to find dynamic library: libcublas.so ( libcublas.so: cannot open shared object file: No such file or directory ) 
 Please specify its path correctly using following ways: 
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
 For instance, issue command: export LD_LIBRARY_PATH=... 
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at (/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:177)

Process finished with exit code 1

**Comment by ZGSLZL** [comment]
Hi， @1282522443 ，what is the version of paddle you are using？try paddle 1.7.1 ?

**Comment by linnnff** [comment]
I can run in my computer with windows,but&nbsp; an error occurred on the server with ubantu16.0。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZGSLZL"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月16日(星期二) 中午12:31
收件人:&nbsp;"VIS-VAR/LGSC-for-FAS"<LGSC-for-FAS@noreply.github.com&gt;;
抄送:&nbsp;"林楠楠"<1282522443@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [VIS-VAR/LGSC-for-FAS] 求大佬帮助 (#17)





 
Hi， @1282522443 ，what is the version of paddle you are using？try paddle 1.7.1 ?

**Comment by xstju** [comment]
> Hi， @1282522443 ，what is the version of paddle you are using？try paddle 1.7.1 ?
why I can't install paddle 1.7.1? My system is centos 7 and cuda9 .  I can only install paddlepaddle-gpu 1.8+ when using conda. 
Please help!

**Comment by xstju** [comment]
> Hi， @1282522443 ，what is the version of paddle you are using？try paddle 1.7.1 ?

How to install paddle1.7.1? I can only install paddle 1.8+ when using pip or conda.
